### ISSUE TITLE
FR: allow requester to work inside Docblocks

### ISSUE THREAD

**Issue by adrienne** [kylebebak/Requester#16]
I just found this plugin and i am _in love_ already. I have one request: I use docblocks a lot, and it would be *super handy* if i could just embed a Requester line directly into the description field and hit `Ctrl+Alt+R` to have it parse (currently it won't; it throws an error because of the leading ` *`). Here's the kind of thing i envision:

```
/**
 * Testing
 * 
 * Blah blah long description
 * API output:
 * requests.get('https://someURL.com/api/v1/departments')
 * 
 * @otherstuff
 * 
 */
```

**Comment by kylebebak** [comment]
Thanks for opening this issue. I've been thinking about it for a few days and thought it would be hard to implement changes to the parser to correctly parse a request like the one in your example, but it's not.

I'll push a new release with this change soon.

**Comment by kylebebak** [comment]
@adrienne 

Pretty sure this is fixed now! Try placing your cursor anywhere on the line with the call to `requests.get` and run Requester.

Closing this issue, let me know if you're having any other trouble.

**Comment by adrienne** [comment]
@kylebebak - Nope, still getting an error. 
![image](https://user-images.githubusercontent.com/89705/47875010-92c42980-ddd2-11e8-938f-3742b405c0f5.png)

**Comment by kylebebak** [comment]
Hmm, could you paste the text, including the surrounding lines, and show me where you're putting your cursor when you run Requester?

**Comment by adrienne** [comment]
@kylebebak - Here's the text:

```
/**
 * Testing
 * 
 * Blah blah long description
 * API output:
 * requests.get('https://api-domain.test/v1/blah', verify=False)
 * 
 * @otherstuff
 * 
 */
```

And it doesn't matter where i put my cursor; i tried at the beginning of the line as well as in the middle.

**Comment by kylebebak** [comment]
Weird!

When I try to execute this request, the error I get is different. Requester parses the request correctly, but there is a connection error because the site doesn't exist.

Check out the error printed to the console at the bottom of the page, and check where my cursor is in the request. I can put my cursor anywhere on that line and it works...

Are you sure you're running Requester v2.28.0? I'm going to try removing my dev copy, installing Requester from Package Control, and seeing what happens.

<img width="1280" alt="screen shot 2018-11-02 at 9 00 38 am" src="https://user-images.githubusercontent.com/1524088/47923238-77165d00-de7e-11e8-92e9-8a5808eea9e3.png">

**Comment by kylebebak** [comment]
So I removed my dev copy of Requester and installed it from Package Control, and I still can't reproduce the bug.

I'm running Requester 2.28.0 and it parses your request just fine. Could you try uninstalling Requester and installing it again?

Or, could you run **Package Control: List Packages** and check that your Requester is at the same version as mine?

<img width="622" alt="screen shot 2018-11-02 at 10 01 51 am" src="https://user-images.githubusercontent.com/1524088/47926545-6cf85c80-de86-11e8-8ea2-538b6b6091e7.png">

**Comment by adrienne** [comment]
@kylebebak Doesn't look like it is the same version? I uninstalled and reinstalled, but this is what i get: 
![image](https://user-images.githubusercontent.com/89705/47977919-bfe13800-e06f-11e8-8ab5-415dfa0f8024.png)

But anyway, i uninstalled and reinstalled, and while I still don't get the same version as your screencap above, it works now. So you can close this!

**Comment by kylebebak** [comment]
Right on!

We're running the same version now, mine is just displayed differently (with a timestamp instead of the version tag).

I'm glad this works now!
